version: '3.9'

services:
  jekyll: 
    image: jekyll/jekyll:3.8.6
    container_name: sanderh.dev.local
    environment:
        - JEKYLL_ENV=docker
    # force_polling makes the linux box watch for any changes to files, then it will regenerate
    # livereload gets the browser to automatically refresh when changes happen to files
    command: >
        bash -c "gem install bundler
        && jekyll serve --force_polling --livereload"
    ports:
        - 4000:4000
        - 35729:35729
    volumes:
        - ./:/srv/jekyll
